-- 01_create_schema.sql (CS5588 final version)

USE WAREHOUSE LEARNER_WH;

USE DATABASE TRAINING_DB;

CREATE SCHEMA IF NOT EXISTS UMKC_RAG;

USE SCHEMA UMKC_RAG;

SELECT CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();
