-- 02_create_tables.sql
-- You should currently be in: TRAINING_DB.UMKC_RAG
-- (If unsure, run: SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();)

USE WAREHOUSE LEARNER_WH;
USE DATABASE TRAINING_DB;
USE SCHEMA UMKC_RAG;

-- 1) Document Metadata Table: One row per PDF
CREATE TABLE IF NOT EXISTS DOCS (
  DOC_ID STRING DEFAULT UUID_STRING(),
  DOC_NAME STRING NOT NULL,
  DOC_SOURCE STRING,
  DOC_TYPE STRING,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_DOCS PRIMARY KEY (DOC_ID)
);

-- 2) Document Chunks Table: One row per text segment
CREATE TABLE IF NOT EXISTS DOC_CHUNKS (
  DOC_ID STRING NOT NULL,
  CHUNK_ID INTEGER NOT NULL,
  CHUNK_TEXT STRING NOT NULL,
  PAGE_NUM INTEGER,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_DOC_CHUNKS PRIMARY KEY (DOC_ID, CHUNK_ID)
);

-- 3) Embedding Feature Table: One row per chunk embedding
-- Note: EMBEDDING is stored as an ARRAY (used when writing back from Python)
CREATE TABLE IF NOT EXISTS CHUNK_EMBEDDINGS (
  DOC_ID STRING NOT NULL,
  CHUNK_ID INTEGER NOT NULL,
  EMBEDDING ARRAY NOT NULL,
  EMBEDDING_MODEL STRING NOT NULL,
  EMBEDDING_VERSION STRING NOT NULL,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_CHUNK_EMBEDDINGS PRIMARY KEY (DOC_ID, CHUNK_ID, EMBEDDING_MODEL, EMBEDDING_VERSION)
);

-- 4) Pipeline Logs Table: Tracks execution of ingestion, embedding, and queries
CREATE TABLE IF NOT EXISTS PIPELINE_LOGS (
  RUN_ID STRING NOT NULL,
  STAGE STRING NOT NULL,
  STATUS STRING NOT NULL,
  ROWS_IN INTEGER,
  ROWS_OUT INTEGER,
  LATENCY_MS INTEGER,
  ERROR_MESSAGE STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
