USE WAREHOUSE LEARNER_WH;
USE DATABASE TRAINING_DB;
USE SCHEMA UMKC_RAG;

CREATE TABLE IF NOT EXISTS DOC_CHUNKS_RAW (
  DOC_NAME STRING,
  DOC_SOURCE STRING,
  DOC_TYPE STRING,
  PAGE_NUM INTEGER,
  CHUNK_ID INTEGER,
  CHUNK_TEXT STRING,
  CREATED_AT STRING
);

SHOW TABLES;

SELECT COUNT(*) FROM DOC_CHUNKS_RAW;