USE WAREHOUSE LEARNER_WH;
USE DATABASE TRAINING_DB;
USE SCHEMA UMKC_RAG;

CREATE OR REPLACE TABLE DOC_CHUNKS_FEATURED AS
SELECT
    DOC_NAME,
    DOC_SOURCE,
    DOC_TYPE,
    PAGE_NUM,
    CHUNK_ID,
    CHUNK_TEXT,
    LENGTH(CHUNK_TEXT) AS TEXT_LENGTH,
    CREATED_AT
FROM DOC_CHUNKS_RAW
WHERE CHUNK_TEXT IS NOT NULL
  AND LENGTH(CHUNK_TEXT) > 50;

SELECT COUNT(*) FROM DOC_CHUNKS_FEATURED;