USE WAREHOUSE LEARNER_WH;
USE DATABASE TRAINING_DB;
USE SCHEMA UMKC_RAG;

-- 简单检索（Decision Layer）：用户输入 query，用 ILIKE 检索 top chunks
-- 示例把 'parking' 换成你想测试的关键词
SELECT
  DOC_NAME,
  PAGE_NUM,
  CHUNK_ID,
  CHUNK_TEXT,
  TEXT_LENGTH
FROM DOC_CHUNKS_FEATURED
WHERE CHUNK_TEXT ILIKE '%parking%'
ORDER BY TEXT_LENGTH DESC
LIMIT 8;